spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/querydsl
    username: postgres
    password: 1234
  jpa:
    hibernate:
      ddl-auto: create
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    properties:
      hibernate:
#        show_sql: false
        format_sql: true
        use_sql_comments: true

#  data:
#    web:
#      pageable:
#        default-page-size: 10
#        max-page-size: 2000
#        #page 객체의 값은 + 1을 바라보고 만들기 때문에 사용의 한계가 있음
#        one-indexed-parameters: false

logging.level:
  org.hibernate.SQL: debug
  org.hibernate.type: debug
